package org.iie.po;
// Generated 2014-10-17 15:48:45 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * TAppeal generated by hbm2java
 */
public class TAppeal  implements java.io.Serializable {


     private Long appealId;
     private String appealNumber;
     private Byte appealKind;
     private String name;
     private String eid;
     private String idcard;
     private String telphone;
     private String email;
     private byte[] idcardPhoto;
     private byte[] handIdcard;
     private byte[] accountPhoto;
     private byte[] handAccount;
     private String description;
     private Date requestTime;
     private Date modifyTime;
     private Byte status;

    public TAppeal() {
    }

    public TAppeal(String appealNumber, Byte appealKind, String name, String eid, String idcard, String telphone, String email, byte[] idcardPhoto, byte[] handIdcard, byte[] accountPhoto, byte[] handAccount, String description,  Date requestTime, Date modifyTime, Byte status) {
       this.appealNumber = appealNumber;
       this.appealKind = appealKind;
       this.name = name;
       this.eid = eid;
       this.idcard = idcard;
       this.telphone = telphone;
       this.email = email;
       this.idcardPhoto = idcardPhoto;
       this.handIdcard = handIdcard;
       this.accountPhoto = accountPhoto;
       this.handAccount = handAccount;
       this.description = description;
       this.requestTime = requestTime;
       this.modifyTime = modifyTime;
       this.status = status;
    }
   
    public Long getAppealId() {
        return this.appealId;
    }
    
    public void setAppealId(Long appealId) {
        this.appealId = appealId;
    }
    public String getAppealNumber() {
        return this.appealNumber;
    }
    
    public void setAppealNumber(String appealNumber) {
        this.appealNumber = appealNumber;
    }
    public Byte getAppealKind() {
        return this.appealKind;
    }
    
    public void setAppealKind(Byte appealKind) {
        this.appealKind = appealKind;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEid() {
        return this.eid;
    }
    
    public void setEid(String eid) {
        this.eid = eid;
    }
    public String getIdcard() {
        return this.idcard;
    }
    
    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }
    public String getTelphone() {
        return this.telphone;
    }
    
    public void setTelphone(String telphone) {
        this.telphone = telphone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public byte[] getIdcardPhoto() {
        return this.idcardPhoto;
    }
    
    public void setIdcardPhoto(byte[] idcardPhoto) {
        this.idcardPhoto = idcardPhoto;
    }
    public byte[] getHandIdcard() {
        return this.handIdcard;
    }
    
    public void setHandIdcard(byte[] handIdcard) {
        this.handIdcard = handIdcard;
    }
    public byte[] getAccountPhoto() {
        return this.accountPhoto;
    }
    
    public void setAccountPhoto(byte[] accountPhoto) {
        this.accountPhoto = accountPhoto;
    }
    public byte[] getHandAccount() {
        return this.handAccount;
    }
    
    public void setHandAccount(byte[] handAccount) {
        this.handAccount = handAccount;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getRequestTime() {
        return this.requestTime;
    }
    
    public void setRequestTime(Date requestTime) {
        this.requestTime = requestTime;
    }
    public Date getModifyTime() {
        return this.modifyTime;
    }
    
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }




}


